import { Country } from "@/client";

export enum CountryCode {
  AF = "AF",
  AL = "AL",
  DZ = "DZ",
  AS = "AS",
  AD = "AD",
  AO = "AO",
  AI = "AI",
  AQ = "AQ",
  AG = "AG",
  AR = "AR",
  AM = "AM",
  AW = "AW",
  AU = "AU",
  AT = "AT",
  AZ = "AZ",
  BS = "BS",
  BH = "BH",
  BD = "BD",
  BB = "BB",
  BY = "BY",
  BE = "BE",
  BZ = "BZ",
  BJ = "BJ",
  BM = "BM",
  AX = "AX",
  BT = "BT",
  BO = "BO",
  BQ = "BQ",
  BA = "BA",
  BW = "BW",
  BV = "BV",
  BR = "BR",
  IO = "IO",
  BN = "BN",
  BG = "BG",
  BF = "BF",
  BI = "BI",
  CV = "CV",
  KH = "KH",
  CM = "CM",
  CA = "CA",
  KY = "KY",
  CF = "CF",
  TD = "TD",
  CL = "CL",
  CN = "CN",
  CX = "CX",
  CC = "CC",
  CO = "CO",
  KM = "KM",
  CD = "CD",
  CG = "CG",
  CK = "CK",
  CR = "CR",
  HR = "HR",
  CU = "CU",
  CW = "CW",
  CY = "CY",
  CZ = "CZ",
  CI = "CI",
  DK = "DK",
  DJ = "DJ",
  DM = "DM",
  DO = "DO",
  EC = "EC",
  EG = "EG",
  SV = "SV",
  GQ = "GQ",
  ER = "ER",
  EE = "EE",
  SZ = "SZ",
  ET = "ET",
  FK = "FK",
  FO = "FO",
  FJ = "FJ",
  FI = "FI",
  FR = "FR",
  GF = "GF",
  PF = "PF",
  TF = "TF",
  GA = "GA",
  GM = "GM",
  GE = "GE",
  DE = "DE",
  GH = "GH",
  GI = "GI",
  GR = "GR",
  GL = "GL",
  GD = "GD",
  GP = "GP",
  GU = "GU",
  GT = "GT",
  GG = "GG",
  GN = "GN",
  GW = "GW",
  GY = "GY",
  HT = "HT",
  HM = "HM",
  VA = "VA",
  HN = "HN",
  HK = "HK",
  HU = "HU",
  IS = "IS",
  IN = "IN",
  ID = "ID",
  IR = "IR",
  IQ = "IQ",
  IE = "IE",
  IM = "IM",
  IL = "IL",
  IT = "IT",
  JM = "JM",
  JP = "JP",
  JE = "JE",
  JO = "JO",
  KZ = "KZ",
  KE = "KE",
  KI = "KI",
  KP = "KP",
  KR = "KR",
  KW = "KW",
  KG = "KG",
  LA = "LA",
  LV = "LV",
  LB = "LB",
  LS = "LS",
  LR = "LR",
  LY = "LY",
  LI = "LI",
  LT = "LT",
  LU = "LU",
  MO = "MO",
  MG = "MG",
  MW = "MW",
  MY = "MY",
  MV = "MV",
  ML = "ML",
  MT = "MT",
  MH = "MH",
  MQ = "MQ",
  MR = "MR",
  MU = "MU",
  YT = "YT",
  MX = "MX",
  FM = "FM",
  MD = "MD",
  MC = "MC",
  MN = "MN",
  ME = "ME",
  MS = "MS",
  MA = "MA",
  MZ = "MZ",
  MM = "MM",
  NA = "NA",
  NR = "NR",
  NP = "NP",
  NL = "NL",
  NC = "NC",
  NZ = "NZ",
  NI = "NI",
  NE = "NE",
  NG = "NG",
  NU = "NU",
  NF = "NF",
  MK = "MK",
  MP = "MP",
  NO = "NO",
  OM = "OM",
  PK = "PK",
  PW = "PW",
  PS = "PS",
  PA = "PA",
  PG = "PG",
  PY = "PY",
  PE = "PE",
  PH = "PH",
  PN = "PN",
  PL = "PL",
  PT = "PT",
  PR = "PR",
  QA = "QA",
  RO = "RO",
  RU = "RU",
  RW = "RW",
  RE = "RE",
  BL = "BL",
  SH = "SH",
  KN = "KN",
  LC = "LC",
  MF = "MF",
  PM = "PM",
  VC = "VC",
  WS = "WS",
  SM = "SM",
  ST = "ST",
  SA = "SA",
  SN = "SN",
  RS = "RS",
  SC = "SC",
  SL = "SL",
  SG = "SG",
  SX = "SX",
  SK = "SK",
  SI = "SI",
  SB = "SB",
  SO = "SO",
  ZA = "ZA",
  GS = "GS",
  SS = "SS",
  ES = "ES",
  LK = "LK",
  SD = "SD",
  SR = "SR",
  SJ = "SJ",
  SE = "SE",
  CH = "CH",
  SY = "SY",
  TW = "TW",
  TJ = "TJ",
  TZ = "TZ",
  TH = "TH",
  TL = "TL",
  TG = "TG",
  TK = "TK",
  TO = "TO",
  TT = "TT",
  TN = "TN",
  TR = "TR",
  TM = "TM",
  TC = "TC",
  TV = "TV",
  UG = "UG",
  UA = "UA",
  AE = "AE",
  GB = "GB",
  US = "US",
  UM = "UM",
  UY = "UY",
  UZ = "UZ",
  VU = "VU",
  VE = "VE",
  VN = "VN",
  VG = "VG",
  VI = "VI",
  WF = "WF",
  EH = "EH",
  YE = "YE",
  ZM = "ZM",
  ZW = "ZW",
  XK = "XK",
}

export const Countries: { [key in keyof typeof CountryCode]: Country } = {
  [CountryCode.AF]: {
    code: "AF",
    code_a3: "AFG",
    code_n3: "004",
    name: "افغانستان",
  },
  [CountryCode.AL]: {
    code: "AL",
    code_a3: "ALB",
    code_n3: "008",
    name: "Shqipëri",
  },
  [CountryCode.DZ]: {
    code: "DZ",
    code_a3: "DZA",
    code_n3: "012",
    name: "الجزائر",
  },
  [CountryCode.AS]: {
    code: "AS",
    code_a3: "ASM",
    code_n3: "016",
    name: "American Samoa",
  },
  [CountryCode.AD]: {
    code: "AD",
    code_a3: "AND",
    code_n3: "020",
    name: "Andorra",
  },
  [CountryCode.AO]: {
    code: "AO",
    code_a3: "AGO",
    code_n3: "024",
    name: "Angola",
  },
  [CountryCode.AI]: {
    code: "AI",
    code_a3: "AIA",
    code_n3: "660",
    name: "Anguilla",
  },
  [CountryCode.AQ]: {
    code: "AQ",
    code_a3: "ATA",
    code_n3: "010",
    name: "Antarctica",
  },
  [CountryCode.AG]: {
    code: "AG",
    code_a3: "ATG",
    code_n3: "028",
    name: "Antigua and Barbuda",
  },
  [CountryCode.AR]: {
    code: "AR",
    code_a3: "ARG",
    code_n3: "032",
    name: "Argentina",
  },
  [CountryCode.AM]: {
    code: "AM",
    code_a3: "ARM",
    code_n3: "051",
    name: "Հայաստան",
  },
  [CountryCode.AW]: {
    code: "AW",
    code_a3: "ABW",
    code_n3: "533",
    name: "Aruba",
  },
  [CountryCode.AU]: {
    code: "AU",
    code_a3: "AUS",
    code_n3: "036",
    name: "Australia",
  },
  [CountryCode.AT]: {
    code: "AT",
    code_a3: "AUT",
    code_n3: "040",
    name: "Österreich",
  },
  [CountryCode.AZ]: {
    code: "AZ",
    code_a3: "AZE",
    code_n3: "031",
    name: "Azərbaycan",
  },
  [CountryCode.BS]: {
    code: "BS",
    code_a3: "BHS",
    code_n3: "044",
    name: "Bahamas",
  },
  [CountryCode.BH]: {
    code: "BH",
    code_a3: "BHR",
    code_n3: "048",
    name: "البحرين",
  },
  [CountryCode.BD]: {
    code: "BD",
    code_a3: "BGD",
    code_n3: "050",
    name: "বাংলাদেশ",
  },
  [CountryCode.BB]: {
    code: "BB",
    code_a3: "BRB",
    code_n3: "052",
    name: "Barbados",
  },
  [CountryCode.BY]: {
    code: "BY",
    code_a3: "BLR",
    code_n3: "112",
    name: "Беларусь",
  },
  [CountryCode.BE]: {
    code: "BE",
    code_a3: "BEL",
    code_n3: "056",
    name: "België/Belgique/Belgien",
  },
  [CountryCode.BZ]: {
    code: "BZ",
    code_a3: "BLZ",
    code_n3: "084",
    name: "Belize",
  },
  [CountryCode.BJ]: {
    code: "BJ",
    code_a3: "BEN",
    code_n3: "204",
    name: "Bénin",
  },
  [CountryCode.BM]: {
    code: "BM",
    code_a3: "BMU",
    code_n3: "060",
    name: "Bermuda",
  },
  [CountryCode.AX]: {
    code: "AX",
    code_a3: "ALA",
    code_n3: "248",
    name: "Åland",
  },
  [CountryCode.BT]: {
    code: "BT",
    code_a3: "BTN",
    code_n3: "064",
    name: "འབྲུག་ཡུལ་",
  },
  [CountryCode.BO]: {
    code: "BO",
    code_a3: "BOL",
    code_n3: "068",
    name: "Bolivia",
  },
  [CountryCode.BQ]: {
    code: "BQ",
    code_a3: "BES",
    code_n3: "535",
    name: "Bonaire, Sint Eustatius and Saba",
  },
  [CountryCode.BA]: {
    code: "BA",
    code_a3: "BIH",
    code_n3: "070",
    name: "Босна и Херцеговина",
  },
  [CountryCode.BW]: {
    code: "BW",
    code_a3: "BWA",
    code_n3: "072",
    name: "Botswana",
  },
  [CountryCode.BV]: {
    code: "BV",
    code_a3: "BVT",
    code_n3: "074",
    name: "Bouvetøya",
  },
  [CountryCode.BR]: {
    code: "BR",
    code_a3: "BRA",
    code_n3: "076",
    name: "Brasil",
  },
  [CountryCode.IO]: {
    code: "IO",
    code_a3: "IOT",
    code_n3: "086",
    name: "British Indian Ocean Territory",
  },
  [CountryCode.BN]: {
    code: "BN",
    code_a3: "BRN",
    code_n3: "096",
    name: "بروني",
  },
  [CountryCode.BG]: {
    code: "BG",
    code_a3: "BGR",
    code_n3: "100",
    name: "България",
  },
  [CountryCode.BF]: {
    code: "BF",
    code_a3: "BFA",
    code_n3: "854",
    name: "Burkina Faso",
  },
  [CountryCode.BI]: {
    code: "BI",
    code_a3: "BDI",
    code_n3: "108",
    name: "Uburundi",
  },
  [CountryCode.CV]: {
    code: "CV",
    code_a3: "CPV",
    code_n3: "132",
    name: "Cabo Verde",
  },
  [CountryCode.KH]: {
    code: "KH",
    code_a3: "KHM",
    code_n3: "116",
    name: "កម្ពុជា",
  },
  [CountryCode.CM]: {
    code: "CM",
    code_a3: "CMR",
    code_n3: "120",
    name: "Cameroun",
  },
  [CountryCode.CA]: {
    code: "CA",
    code_a3: "CAN",
    code_n3: "124",
    name: "Canada",
  },
  [CountryCode.KY]: {
    code: "KY",
    code_a3: "CYM",
    code_n3: "136",
    name: "Cayman Islands",
  },
  [CountryCode.CF]: {
    code: "CF",
    code_a3: "CAF",
    code_n3: "140",
    name: "République centrafricaine",
  },
  [CountryCode.TD]: {
    code: "TD",
    code_a3: "TCD",
    code_n3: "148",
    name: "Tchad",
  },
  [CountryCode.CL]: {
    code: "CL",
    code_a3: "CHL",
    code_n3: "152",
    name: "Chile",
  },
  [CountryCode.CN]: {
    code: "CN",
    code_a3: "CHN",
    code_n3: "156",
    name: "中国",
  },
  [CountryCode.CX]: {
    code: "CX",
    code_a3: "CXR",
    code_n3: "162",
    name: "Christmas Island",
  },
  [CountryCode.CC]: {
    code: "CC",
    code_a3: "CCK",
    code_n3: "166",
    name: "Cocos (Keeling}, Islands",
  },
  [CountryCode.CO]: {
    code: "CO",
    code_a3: "COL",
    code_n3: "170",
    name: "Colombia",
  },
  [CountryCode.KM]: {
    code: "KM",
    code_a3: "COM",
    code_n3: "174",
    name: "Comores",
  },
  [CountryCode.CD]: {
    code: "CD",
    code_a3: "COD",
    code_n3: "180",
    name: "République démocratique du Congo",
  },
  [CountryCode.CG]: {
    code: "CG",
    code_a3: "COG",
    code_n3: "178",
    name: "République du Congo",
  },
  [CountryCode.CK]: {
    code: "CK",
    code_a3: "COK",
    code_n3: "184",
    name: "Cook Islands",
  },
  [CountryCode.CR]: {
    code: "CR",
    code_a3: "CRI",
    code_n3: "188",
    name: "Costa Rica",
  },
  [CountryCode.HR]: {
    code: "HR",
    code_a3: "HRV",
    code_n3: "191",
    name: "Hrvatska",
  },
  [CountryCode.CU]: {
    code: "CU",
    code_a3: "CUB",
    code_n3: "192",
    name: "Cuba",
  },
  [CountryCode.CW]: {
    code: "CW",
    code_a3: "CUW",
    code_n3: "531",
    name: "Curaçao",
  },
  [CountryCode.CY]: {
    code: "CY",
    code_a3: "CYP",
    code_n3: "196",
    name: "Κύπρος",
  },
  [CountryCode.CZ]: {
    code: "CZ",
    code_a3: "CZE",
    code_n3: "203",
    name: "Česko",
  },
  [CountryCode.CI]: {
    code: "CI",
    code_a3: "CIV",
    code_n3: "384",
    name: "Côte d'Ivoire",
  },
  [CountryCode.DK]: {
    code: "DK",
    code_a3: "DNK",
    code_n3: "208",
    name: "Danmark",
  },
  [CountryCode.DJ]: {
    code: "DJ",
    code_a3: "DJI",
    code_n3: "262",
    name: "Djibouti",
  },
  [CountryCode.DM]: {
    code: "DM",
    code_a3: "DMA",
    code_n3: "212",
    name: "Dominica",
  },
  [CountryCode.DO]: {
    code: "DO",
    code_a3: "DOM",
    code_n3: "214",
    name: "República Dominicana",
  },
  [CountryCode.EC]: {
    code: "EC",
    code_a3: "ECU",
    code_n3: "218",
    name: "Ecuador",
  },
  [CountryCode.EG]: { code: "EG", code_a3: "EGY", code_n3: "818", name: "مصر" },
  [CountryCode.SV]: {
    code: "SV",
    code_a3: "SLV",
    code_n3: "222",
    name: "El Salvador",
  },
  [CountryCode.GQ]: {
    code: "GQ",
    code_a3: "GNQ",
    code_n3: "226",
    name: "Guinea Ecuatorial",
  },
  [CountryCode.ER]: {
    code: "ER",
    code_a3: "ERI",
    code_n3: "232",
    name: "ኤርትራ",
  },
  [CountryCode.EE]: {
    code: "EE",
    code_a3: "EST",
    code_n3: "233",
    name: "Eesti",
  },
  [CountryCode.SZ]: {
    code: "SZ",
    code_a3: "SWZ",
    code_n3: "748",
    name: "Eswatini",
  },
  [CountryCode.ET]: {
    code: "ET",
    code_a3: "ETH",
    code_n3: "231",
    name: "ኢትዮጵያ",
  },
  [CountryCode.FK]: {
    code: "FK",
    code_a3: "FLK",
    code_n3: "238",
    name: "Falkland Islands",
  },
  [CountryCode.FO]: {
    code: "FO",
    code_a3: "FRO",
    code_n3: "234",
    name: "Føroyar",
  },
  [CountryCode.FJ]: {
    code: "FJ",
    code_a3: "FJI",
    code_n3: "242",
    name: "Fiji",
  },
  [CountryCode.FI]: {
    code: "FI",
    code_a3: "FIN",
    code_n3: "246",
    name: "Suomi",
  },
  [CountryCode.FR]: {
    code: "FR",
    code_a3: "FRA",
    code_n3: "250",
    name: "France",
  },
  [CountryCode.GF]: {
    code: "GF",
    code_a3: "GUF",
    code_n3: "254",
    name: "Guyane française",
  },
  [CountryCode.PF]: {
    code: "PF",
    code_a3: "PYF",
    code_n3: "258",
    name: "Polynésie française",
  },
  [CountryCode.TF]: {
    code: "TF",
    code_a3: "ATF",
    code_n3: "260",
    name: "Terres australes et antarctiques françaises",
  },
  [CountryCode.GA]: {
    code: "GA",
    code_a3: "GAB",
    code_n3: "266",
    name: "Gabon",
  },
  [CountryCode.GM]: {
    code: "GM",
    code_a3: "GMB",
    code_n3: "270",
    name: "Gambia",
  },
  [CountryCode.GE]: {
    code: "GE",
    code_a3: "GEO",
    code_n3: "268",
    name: "საქართველო",
  },
  [CountryCode.DE]: {
    code: "DE",
    code_a3: "DEU",
    code_n3: "276",
    name: "Deutschland",
  },
  [CountryCode.GH]: {
    code: "GH",
    code_a3: "GHA",
    code_n3: "288",
    name: "Ghana",
  },
  [CountryCode.GI]: {
    code: "GI",
    code_a3: "GIB",
    code_n3: "292",
    name: "Gibraltar",
  },
  [CountryCode.GR]: {
    code: "GR",
    code_a3: "GRC",
    code_n3: "300",
    name: "Ελλάδα",
  },
  [CountryCode.GL]: {
    code: "GL",
    code_a3: "GRL",
    code_n3: "304",
    name: "Kalaallit Nunaat",
  },
  [CountryCode.GD]: {
    code: "GD",
    code_a3: "GRD",
    code_n3: "308",
    name: "Grenada",
  },
  [CountryCode.GP]: {
    code: "GP",
    code_a3: "GLP",
    code_n3: "312",
    name: "Guadeloupe",
  },
  [CountryCode.GU]: {
    code: "GU",
    code_a3: "GUM",
    code_n3: "316",
    name: "Guam",
  },
  [CountryCode.GT]: {
    code: "GT",
    code_a3: "GTM",
    code_n3: "320",
    name: "Guatemala",
  },
  [CountryCode.GG]: {
    code: "GG",
    code_a3: "GGY",
    code_n3: "831",
    name: "Guernsey",
  },
  [CountryCode.GN]: {
    code: "GN",
    code_a3: "GIN",
    code_n3: "324",
    name: "Guinée",
  },
  [CountryCode.GW]: {
    code: "GW",
    code_a3: "GNB",
    code_n3: "624",
    name: "Guiné-Bissau",
  },
  [CountryCode.GY]: {
    code: "GY",
    code_a3: "GUY",
    code_n3: "328",
    name: "Guyana",
  },
  [CountryCode.HT]: {
    code: "HT",
    code_a3: "HTI",
    code_n3: "332",
    name: "Haïti",
  },
  [CountryCode.HM]: {
    code: "HM",
    code_a3: "HMD",
    code_n3: "334",
    name: "Heard Island and McDonald Islands",
  },
  [CountryCode.VA]: {
    code: "VA",
    code_a3: "VAT",
    code_n3: "336",
    name: "Santa Sede",
  },
  [CountryCode.HN]: {
    code: "HN",
    code_a3: "HND",
    code_n3: "340",
    name: "Honduras",
  },
  [CountryCode.HK]: {
    code: "HK",
    code_a3: "HKG",
    code_n3: "344",
    name: "香港",
  },
  [CountryCode.HU]: {
    code: "HU",
    code_a3: "HUN",
    code_n3: "348",
    name: "Magyarország",
  },
  [CountryCode.IS]: {
    code: "IS",
    code_a3: "ISL",
    code_n3: "352",
    name: "Ísland",
  },
  [CountryCode.IN]: {
    code: "IN",
    code_a3: "IND",
    code_n3: "356",
    name: "भारत",
  },
  [CountryCode.ID]: {
    code: "ID",
    code_a3: "IDN",
    code_n3: "360",
    name: "Indonesia",
  },
  [CountryCode.IR]: {
    code: "IR",
    code_a3: "IRN",
    code_n3: "364",
    name: "ایران",
  },
  [CountryCode.IQ]: {
    code: "IQ",
    code_a3: "IRQ",
    code_n3: "368",
    name: "العراق",
  },
  [CountryCode.IE]: {
    code: "IE",
    code_a3: "IRL",
    code_n3: "372",
    name: "Éire",
  },
  [CountryCode.IM]: {
    code: "IM",
    code_a3: "IMN",
    code_n3: "833",
    name: "Isle of Man",
  },
  [CountryCode.IL]: {
    code: "IL",
    code_a3: "ISR",
    code_n3: "376",
    name: "ישראל",
  },
  [CountryCode.IT]: {
    code: "IT",
    code_a3: "ITA",
    code_n3: "380",
    name: "Italia",
  },
  [CountryCode.JM]: {
    code: "JM",
    code_a3: "JAM",
    code_n3: "388",
    name: "Jamaica",
  },
  [CountryCode.JP]: {
    code: "JP",
    code_a3: "JPN",
    code_n3: "392",
    name: "日本",
  },
  [CountryCode.JE]: {
    code: "JE",
    code_a3: "JEY",
    code_n3: "832",
    name: "Jersey",
  },
  [CountryCode.JO]: {
    code: "JO",
    code_a3: "JOR",
    code_n3: "400",
    name: "الأردن",
  },
  [CountryCode.KZ]: {
    code: "KZ",
    code_a3: "KAZ",
    code_n3: "398",
    name: "Қазақстан",
  },
  [CountryCode.KE]: {
    code: "KE",
    code_a3: "KEN",
    code_n3: "404",
    name: "Kenya",
  },
  [CountryCode.KI]: {
    code: "KI",
    code_a3: "KIR",
    code_n3: "296",
    name: "Kiribati",
  },
  [CountryCode.KP]: {
    code: "KP",
    code_a3: "PRK",
    code_n3: "408",
    name: "조선민주주의인민공화국",
  },
  [CountryCode.KR]: {
    code: "KR",
    code_a3: "KOR",
    code_n3: "410",
    name: "대한민국",
  },
  [CountryCode.KW]: {
    code: "KW",
    code_a3: "KWT",
    code_n3: "414",
    name: "الكويت",
  },
  [CountryCode.KG]: {
    code: "KG",
    code_a3: "KGZ",
    code_n3: "417",
    name: "Кыргызстан",
  },
  [CountryCode.LA]: { code: "LA", code_a3: "LAO", code_n3: "418", name: "ລາວ" },
  [CountryCode.LV]: {
    code: "LV",
    code_a3: "LVA",
    code_n3: "428",
    name: "Latvija",
  },
  [CountryCode.LB]: {
    code: "LB",
    code_a3: "LBN",
    code_n3: "422",
    name: "لبنان",
  },
  [CountryCode.LS]: {
    code: "LS",
    code_a3: "LSO",
    code_n3: "426",
    name: "Lesotho",
  },
  [CountryCode.LR]: {
    code: "LR",
    code_a3: "LBR",
    code_n3: "430",
    name: "Liberia",
  },
  [CountryCode.LY]: {
    code: "LY",
    code_a3: "LBY",
    code_n3: "434",
    name: "ليبيا",
  },
  [CountryCode.LI]: {
    code: "LI",
    code_a3: "LIE",
    code_n3: "438",
    name: "Liechtenstein",
  },
  [CountryCode.LT]: {
    code: "LT",
    code_a3: "LTU",
    code_n3: "440",
    name: "Lietuva",
  },
  [CountryCode.LU]: {
    code: "LU",
    code_a3: "LUX",
    code_n3: "442",
    name: "Luxembourg",
  },
  [CountryCode.MO]: {
    code: "MO",
    code_a3: "MAC",
    code_n3: "446",
    name: "澳門",
  },
  [CountryCode.MG]: {
    code: "MG",
    code_a3: "MDG",
    code_n3: "450",
    name: "Madagasikara",
  },
  [CountryCode.MW]: {
    code: "MW",
    code_a3: "MWI",
    code_n3: "454",
    name: "Malawi",
  },
  [CountryCode.MY]: {
    code: "MY",
    code_a3: "MYS",
    code_n3: "458",
    name: "Malaysia",
  },
  [CountryCode.MV]: {
    code: "MV",
    code_a3: "MDV",
    code_n3: "462",
    name: "ދިވެހިރާއްޖެހޭނެ",
  },
  [CountryCode.ML]: {
    code: "ML",
    code_a3: "MLI",
    code_n3: "466",
    name: "Mali",
  },
  [CountryCode.MT]: {
    code: "MT",
    code_a3: "MLT",
    code_n3: "470",
    name: "Malta",
  },
  [CountryCode.MH]: {
    code: "MH",
    code_a3: "MHL",
    code_n3: "584",
    name: "M̧ajeļ",
  },
  [CountryCode.MQ]: {
    code: "MQ",
    code_a3: "MTQ",
    code_n3: "474",
    name: "Martinique",
  },
  [CountryCode.MR]: {
    code: "MR",
    code_a3: "MRT",
    code_n3: "478",
    name: "موريتانيا",
  },
  [CountryCode.MU]: {
    code: "MU",
    code_a3: "MUS",
    code_n3: "480",
    name: "Maurice",
  },
  [CountryCode.YT]: {
    code: "YT",
    code_a3: "MYT",
    code_n3: "175",
    name: "Mayotte",
  },
  [CountryCode.MX]: {
    code: "MX",
    code_a3: "MEX",
    code_n3: "484",
    name: "México",
  },
  [CountryCode.FM]: {
    code: "FM",
    code_a3: "FSM",
    code_n3: "583",
    name: "Micronesia",
  },
  [CountryCode.MD]: {
    code: "MD",
    code_a3: "MDA",
    code_n3: "498",
    name: "Moldova",
  },
  [CountryCode.MC]: {
    code: "MC",
    code_a3: "MCO",
    code_n3: "492",
    name: "Monaco",
  },
  [CountryCode.MN]: {
    code: "MN",
    code_a3: "MNG",
    code_n3: "496",
    name: "Монгол улс",
  },
  [CountryCode.ME]: {
    code: "ME",
    code_a3: "MNE",
    code_n3: "499",
    name: "Црна Гора",
  },
  [CountryCode.MS]: {
    code: "MS",
    code_a3: "MSR",
    code_n3: "500",
    name: "Montserrat",
  },
  [CountryCode.MA]: {
    code: "MA",
    code_a3: "MAR",
    code_n3: "504",
    name: "المغرب",
  },
  [CountryCode.MZ]: {
    code: "MZ",
    code_a3: "MOZ",
    code_n3: "508",
    name: "Moçambique",
  },
  [CountryCode.MM]: {
    code: "MM",
    code_a3: "MMR",
    code_n3: "104",
    name: "မြန်မာ",
  },
  [CountryCode.NA]: {
    code: "NA",
    code_a3: "NAM",
    code_n3: "516",
    name: "Namibia",
  },
  [CountryCode.NR]: {
    code: "NR",
    code_a3: "NRU",
    code_n3: "520",
    name: "Nauru",
  },
  [CountryCode.NP]: {
    code: "NP",
    code_a3: "NPL",
    code_n3: "524",
    name: "नेपाल",
  },
  [CountryCode.NL]: {
    code: "NL",
    code_a3: "NLD",
    code_n3: "528",
    name: "Nederland",
  },
  [CountryCode.NC]: {
    code: "NC",
    code_a3: "NCL",
    code_n3: "540",
    name: "Nouvelle-Calédonie",
  },
  [CountryCode.NZ]: {
    code: "NZ",
    code_a3: "NZL",
    code_n3: "554",
    name: "New Zealand",
  },
  [CountryCode.NI]: {
    code: "NI",
    code_a3: "NIC",
    code_n3: "558",
    name: "Nicaragua",
  },
  [CountryCode.NE]: {
    code: "NE",
    code_a3: "NER",
    code_n3: "562",
    name: "Niger",
  },
  [CountryCode.NG]: {
    code: "NG",
    code_a3: "NGA",
    code_n3: "566",
    name: "Nigeria",
  },
  [CountryCode.NU]: {
    code: "NU",
    code_a3: "NIU",
    code_n3: "570",
    name: "Niue",
  },
  [CountryCode.NF]: {
    code: "NF",
    code_a3: "NFK",
    code_n3: "574",
    name: "Norfolk Island",
  },
  [CountryCode.MK]: {
    code: "MK",
    code_a3: "MKD",
    code_n3: "807",
    name: "Северна Македонија",
  },
  [CountryCode.MP]: {
    code: "MP",
    code_a3: "MNP",
    code_n3: "580",
    name: "Northern Mariana Islands",
  },
  [CountryCode.NO]: {
    code: "NO",
    code_a3: "NOR",
    code_n3: "578",
    name: "Norge",
  },
  [CountryCode.OM]: {
    code: "OM",
    code_a3: "OMN",
    code_n3: "512",
    name: "عمان",
  },
  [CountryCode.PK]: {
    code: "PK",
    code_a3: "PAK",
    code_n3: "586",
    name: "پاکستان",
  },
  [CountryCode.PW]: {
    code: "PW",
    code_a3: "PLW",
    code_n3: "585",
    name: "Palau",
  },
  [CountryCode.PS]: {
    code: "PS",
    code_a3: "PSE",
    code_n3: "275",
    name: "فلسطين",
  },
  [CountryCode.PA]: {
    code: "PA",
    code_a3: "PAN",
    code_n3: "591",
    name: "Panamá",
  },
  [CountryCode.PG]: {
    code: "PG",
    code_a3: "PNG",
    code_n3: "598",
    name: "Papua Niugini",
  },
  [CountryCode.PY]: {
    code: "PY",
    code_a3: "PRY",
    code_n3: "600",
    name: "Paraguay",
  },
  [CountryCode.PE]: {
    code: "PE",
    code_a3: "PER",
    code_n3: "604",
    name: "Perú",
  },
  [CountryCode.PH]: {
    code: "PH",
    code_a3: "PHL",
    code_n3: "608",
    name: "Pilipinas",
  },
  [CountryCode.PN]: {
    code: "PN",
    code_a3: "PCN",
    code_n3: "612",
    name: "Pitcairn",
  },
  [CountryCode.PL]: {
    code: "PL",
    code_a3: "POL",
    code_n3: "616",
    name: "Polska",
  },
  [CountryCode.PT]: {
    code: "PT",
    code_a3: "PRT",
    code_n3: "620",
    name: "Portugal",
  },
  [CountryCode.PR]: {
    code: "PR",
    code_a3: "PRI",
    code_n3: "630",
    name: "Puerto Rico",
  },
  [CountryCode.QA]: { code: "QA", code_a3: "QAT", code_n3: "634", name: "قطر" },
  [CountryCode.RO]: {
    code: "RO",
    code_a3: "ROU",
    code_n3: "642",
    name: "România",
  },
  [CountryCode.RU]: {
    code: "RU",
    code_a3: "RUS",
    code_n3: "643",
    name: "Россия",
  },
  [CountryCode.RW]: {
    code: "RW",
    code_a3: "RWA",
    code_n3: "646",
    name: "Rwanda",
  },
  [CountryCode.RE]: {
    code: "RE",
    code_a3: "REU",
    code_n3: "638",
    name: "Réunion",
  },
  [CountryCode.BL]: {
    code: "BL",
    code_a3: "BLM",
    code_n3: "652",
    name: "Saint-Barthélemy",
  },
  [CountryCode.SH]: {
    code: "SH",
    code_a3: "SHN",
    code_n3: "654",
    name: "Saint Helena, Ascension and Tristan da Cunha",
  },
  [CountryCode.KN]: {
    code: "KN",
    code_a3: "KNA",
    code_n3: "659",
    name: "Saint Kitts and Nevis",
  },
  [CountryCode.LC]: {
    code: "LC",
    code_a3: "LCA",
    code_n3: "662",
    name: "Saint Lucia",
  },
  [CountryCode.MF]: {
    code: "MF",
    code_a3: "MAF",
    code_n3: "663",
    name: "Saint-Martin",
  },
  [CountryCode.PM]: {
    code: "PM",
    code_a3: "SPM",
    code_n3: "666",
    name: "Saint-Pierre-et-Miquelon",
  },
  [CountryCode.VC]: {
    code: "VC",
    code_a3: "VCT",
    code_n3: "670",
    name: "Saint Vincent and the Grenadines",
  },
  [CountryCode.WS]: {
    code: "WS",
    code_a3: "WSM",
    code_n3: "882",
    name: "Samoa",
  },
  [CountryCode.SM]: {
    code: "SM",
    code_a3: "SMR",
    code_n3: "674",
    name: "San Marino",
  },
  [CountryCode.ST]: {
    code: "ST",
    code_a3: "STP",
    code_n3: "678",
    name: "São Tomé e Príncipe",
  },
  [CountryCode.SA]: {
    code: "SA",
    code_a3: "SAU",
    code_n3: "682",
    name: "المملكة العربية السعودية",
  },
  [CountryCode.SN]: {
    code: "SN",
    code_a3: "SEN",
    code_n3: "686",
    name: "Sénégal",
  },
  [CountryCode.RS]: {
    code: "RS",
    code_a3: "SRB",
    code_n3: "688",
    name: "Србија",
  },
  [CountryCode.SC]: {
    code: "SC",
    code_a3: "SYC",
    code_n3: "690",
    name: "Seychelles",
  },
  [CountryCode.SL]: {
    code: "SL",
    code_a3: "SLE",
    code_n3: "694",
    name: "Sierra Leone",
  },
  [CountryCode.SG]: {
    code: "SG",
    code_a3: "SGP",
    code_n3: "702",
    name: "Singapore",
  },
  [CountryCode.SX]: {
    code: "SX",
    code_a3: "SXM",
    code_n3: "534",
    name: "Sint Maarten",
  },
  [CountryCode.SK]: {
    code: "SK",
    code_a3: "SVK",
    code_n3: "703",
    name: "Slovensko",
  },
  [CountryCode.SI]: {
    code: "SI",
    code_a3: "SVN",
    code_n3: "705",
    name: "Slovenija",
  },
  [CountryCode.SB]: {
    code: "SB",
    code_a3: "SLB",
    code_n3: "090",
    name: "Solomon Islands",
  },
  [CountryCode.SO]: {
    code: "SO",
    code_a3: "SOM",
    code_n3: "706",
    name: "Soomaaliya",
  },
  [CountryCode.ZA]: {
    code: "ZA",
    code_a3: "ZAF",
    code_n3: "710",
    name: "South Africa",
  },
  [CountryCode.GS]: {
    code: "GS",
    code_a3: "SGS",
    code_n3: "239",
    name: "South Georgia and the South Sandwich Islands",
  },
  [CountryCode.SS]: {
    code: "SS",
    code_a3: "SSD",
    code_n3: "728",
    name: "جنوب السودان",
  },
  [CountryCode.ES]: {
    code: "ES",
    code_a3: "ESP",
    code_n3: "724",
    name: "España",
  },
  [CountryCode.LK]: {
    code: "LK",
    code_a3: "LKA",
    code_n3: "144",
    name: "ශ්‍රී ලංකාව / இலங்கை",
  },
  [CountryCode.SD]: {
    code: "SD",
    code_a3: "SDN",
    code_n3: "729",
    name: "السودان",
  },
  [CountryCode.SR]: {
    code: "SR",
    code_a3: "SUR",
    code_n3: "740",
    name: "Suriname",
  },
  [CountryCode.SJ]: {
    code: "SJ",
    code_a3: "SJM",
    code_n3: "744",
    name: "Svalbard og Jan Mayen",
  },
  [CountryCode.SE]: {
    code: "SE",
    code_a3: "SWE",
    code_n3: "752",
    name: "Sverige",
  },
  [CountryCode.CH]: {
    code: "CH",
    code_a3: "CHE",
    code_n3: "756",
    name: "Schweiz / Suisse / Svizzera",
  },
  [CountryCode.SY]: {
    code: "SY",
    code_a3: "SYR",
    code_n3: "760",
    name: "سوريا",
  },
  [CountryCode.TW]: {
    code: "TW",
    code_a3: "TWN",
    code_n3: "158",
    name: "臺灣",
  },
  [CountryCode.TJ]: {
    code: "TJ",
    code_a3: "TJK",
    code_n3: "762",
    name: "Тоҷикистон",
  },
  [CountryCode.TZ]: {
    code: "TZ",
    code_a3: "TZA",
    code_n3: "834",
    name: "Tanzania",
  },
  [CountryCode.TH]: {
    code: "TH",
    code_a3: "THA",
    code_n3: "764",
    name: "ประเทศไทย",
  },
  [CountryCode.TL]: {
    code: "TL",
    code_a3: "TLS",
    code_n3: "626",
    name: "Timor-Leste",
  },
  [CountryCode.TG]: {
    code: "TG",
    code_a3: "TGO",
    code_n3: "768",
    name: "Togo",
  },
  [CountryCode.TK]: {
    code: "TK",
    code_a3: "TKL",
    code_n3: "772",
    name: "Tokelau",
  },
  [CountryCode.TO]: {
    code: "TO",
    code_a3: "TON",
    code_n3: "776",
    name: "Tonga",
  },
  [CountryCode.TT]: {
    code: "TT",
    code_a3: "TTO",
    code_n3: "780",
    name: "Trinidad and Tobago",
  },
  [CountryCode.TN]: {
    code: "TN",
    code_a3: "TUN",
    code_n3: "788",
    name: "تونس",
  },
  [CountryCode.TR]: {
    code: "TR",
    code_a3: "TUR",
    code_n3: "792",
    name: "Türkiye",
  },
  [CountryCode.TM]: {
    code: "TM",
    code_a3: "TKM",
    code_n3: "795",
    name: "Türkmenistan",
  },
  [CountryCode.TC]: {
    code: "TC",
    code_a3: "TCA",
    code_n3: "796",
    name: "Turks and Caicos Islands",
  },
  [CountryCode.TV]: {
    code: "TV",
    code_a3: "TUV",
    code_n3: "798",
    name: "Tuvalu",
  },
  [CountryCode.UG]: {
    code: "UG",
    code_a3: "UGA",
    code_n3: "800",
    name: "Uganda",
  },
  [CountryCode.UA]: {
    code: "UA",
    code_a3: "UKR",
    code_n3: "804",
    name: "Україна",
  },
  [CountryCode.AE]: {
    code: "AE",
    code_a3: "ARE",
    code_n3: "784",
    name: "الإمارات العربية المتحدة",
  },
  [CountryCode.GB]: {
    code: "GB",
    code_a3: "GBR",
    code_n3: "826",
    name: "United Kingdom",
  },
  [CountryCode.US]: {
    code: "US",
    code_a3: "USA",
    code_n3: "840",
    name: "United States",
  },
  [CountryCode.UM]: {
    code: "UM",
    code_a3: "UMI",
    code_n3: "581",
    name: "United States Minor Outlying Islands",
  },
  [CountryCode.UY]: {
    code: "UY",
    code_a3: "URY",
    code_n3: "858",
    name: "Uruguay",
  },
  [CountryCode.UZ]: {
    code: "UZ",
    code_a3: "UZB",
    code_n3: "860",
    name: "O‘zbekiston",
  },
  [CountryCode.VU]: {
    code: "VU",
    code_a3: "VUT",
    code_n3: "548",
    name: "Vanuatu",
  },
  [CountryCode.VE]: {
    code: "VE",
    code_a3: "VEN",
    code_n3: "862",
    name: "Venezuela",
  },
  [CountryCode.VN]: {
    code: "VN",
    code_a3: "VNM",
    code_n3: "704",
    name: "Việt Nam",
  },
  [CountryCode.VG]: {
    code: "VG",
    code_a3: "VGB",
    code_n3: "092",
    name: "Virgin Islands (British},",
  },
  [CountryCode.VI]: {
    code: "VI",
    code_a3: "VIR",
    code_n3: "850",
    name: "Virgin Islands (U.S.},",
  },
  [CountryCode.WF]: {
    code: "WF",
    code_a3: "WLF",
    code_n3: "876",
    name: "Wallis et Futuna",
  },
  [CountryCode.EH]: {
    code: "EH",
    code_a3: "ESH",
    code_n3: "732",
    name: "الصحراء الغربية",
  },
  [CountryCode.YE]: {
    code: "YE",
    code_a3: "YEM",
    code_n3: "887",
    name: "اليمن",
  },
  [CountryCode.ZM]: {
    code: "ZM",
    code_a3: "ZMB",
    code_n3: "894",
    name: "Zambia",
  },
  [CountryCode.ZW]: {
    code: "ZW",
    code_a3: "ZWE",
    code_n3: "716",
    name: "Zimbabwe",
  },
  [CountryCode.XK]: {
    code: "XK",
    code_a3: "None",
    code_n3: "None",
    name: "Kosova",
  },
};
